routes/web.php
<?php

use App\Http\Controllers\EmailController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\TeacherController;
use App\Http\Middleware\Authenticate;
use App\Http\Middleware\VerifyUserRole;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/*
|--------------------------------------------------------------------------
| Landing route and landing page
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return view('landing');
})->name('landing');

/*
|--------------------------------------------------------------------------
| Authentication routes and landing page
|--------------------------------------------------------------------------
*/

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(Authenticate::class)->group(function () {
    /*
    |--------------------------------------------------------------------------
    | Courses routes
    |--------------------------------------------------------------------------
    */

    Route::resource('/courses', App\Http\Controllers\CourseController::class);
    Route::get('/course/show_deleted', [App\Http\Controllers\CourseController::class, 'show_deleted'])->name('courses.show_deleted');
    Route::put('/courses/restore/{course}', [App\Http\Controllers\CourseController::class, 'restore'])->name('courses.restore')->withTrashed();

    /*
    |--------------------------------------------------------------------------
    | Workplace routes
    |--------------------------------------------------------------------------
    */

    Route::get('/workplaces/show_deleted', [App\Http\Controllers\WorkplaceController::class, 'show_deleted'])->name('workplaces.show_deleted');
    Route::put('/workplaces/restore/{workplace}', [App\Http\Controllers\WorkplaceController::class, 'restore'])->name('workplaces.restore')->withTrashed();
    Route::resource('/workplaces', App\Http\Controllers\WorkplaceController::class);

    /*
    |--------------------------------------------------------------------------
    | Lessons routes
    |--------------------------------------------------------------------------
    */
    Route::get('/lessons/show_deleted', [App\Http\Controllers\LessonController::class, 'show_deleted'])->name('lessons.show_deleted')->middleware(VerifyUserRole::class);
    Route::get('/lessons/{course}/show_lessons', [App\Http\Controllers\LessonController::class, 'show_lessons'])->name('lessons.show_lessons');
    Route::resource('/lessons', App\Http\Controllers\LessonController::class);


    /*
    |--------------------------------------------------------------------------
    | Authenticated User Routes
    |--------------------------------------------------------------------------
    */

    Route::get('user/{user}/updateprofile', [App\Http\Controllers\UserController::class, 'edit'])->name('user.edit');
    Route::put('user/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('user.update');

    /*
    |--------------------------------------------------------------------------
    | Course Review Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('/review', ReviewController::class);

});





/*
|--------------------------------------------------------------------------
| Info User Routes
|--------------------------------------------------------------------------
*/

Route::resource('/infos', InfoController::class);

//Training facility rental, Internship, Serious games, Web and Software development - aloldalt, controller nélkül
// Cím, egy képnek hely, leírás

//Custom 404 és 403 ->error oldal az oldal stílusában (Ha a workplacesnél a felhasználó role_id != 3 akkor dobjon ide)

// Kapcsolatok aloldal, üzenetküldésre, szerkesztőfelülettel (Cím, 
//alatta bal oldalt szöveg (lionsdale címe, telefon, email elérhetőség, adószám, név, ügyvezető, 
//JOBB oldalt egy kép, 
//ALATTA szövegszerkesztő (ennekcsak egy sort csináljatok és írjátok bele h szövegszerkesztő)))


/*
|--------------------------------------------------------------------------
| Teacher Routes
|--------------------------------------------------------------------------
*/

Route::resource('/teachers', TeacherController::class);

/*
|--------------------------------------------------------------------------
| Email Routes
|--------------------------------------------------------------------------
*/

Route::get('/sendConfirmation', [EmailController::class, 'sendWelcomeEmail']);

app/Models/Workplace.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Workplace extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'location',
        'registrynumber',
        'taxnumber'
    ];


    /* User Connection */
    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/WorkplaceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Workplace;
use App\Http\Requests\StoreWorkplaceRequest;
use App\Http\Requests\UpdateWorkplaceRequest;

class WorkplaceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $workplaces = Workplace::all();
        return view("workplaces.index", ["resources" => $workplaces]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("workplaces.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreWorkplaceRequest $request)
    {
        $workplace = Workplace::create($request->all());
        return redirect()->route("workplaces.index")->with("success", "Workplace created successfully.");

    }

    /**
     * Display the specified resource.
     */
    public function show(Workplace $workplace)
    {
        return view ('workplaces.show', ['workplace' => $workplace]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Workplace $workplace)
    {
        return view("workplaces.edit", ["resource" => $workplace]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateWorkplaceRequest $request, Workplace $workplace)
    {
        $workplace->update($request->all());
        return redirect()->back()->with("success","Update complete.");
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Workplace $workplace)
    {
        $workplace->delete();
        return back()->with("success","Delete Complete");
    }

    public function show_deleted() {
        $deleted_workplaces = Workplace::onlyTrashed()->get();
        return view('workplaces.show_deleted', ['workplaces' => $deleted_workplaces]);
    }

    public function restore(Workplace $workplace) {
        $workplace->restore();
        return redirect()->route('workplaces.index')->with('success', "Workplace restored successfully.");
    }
}

resources/views/workplaces/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card border-secondary">
                <div class="card-body">
                    <h4 class="card-title">Create a Workplace</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('workplaces.store') }}" method="POST">
                        @csrf
                        @method('POST')
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" name="name" id="name" class="form-control @if($errors->has('name')) border border-danger @endif"
                                placeholder="Course Name" aria-describedby="helpId" value="{{old('name')}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-muted">The name of the course to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="location" class="form-label">Location</label>
                            <input type="text" name="location" id="location" class="form-control"
                                placeholder="Address of your company" aria-describedby="helpId" maxlength="255">
                            <small id="helpId" class="text-muted">Short address of the location (255 chars)</small>
                        </div>
                        <div class="mb-3">
                            <label for="registrynumber" class="form-label">Registry number</label>
                            <input type="text" name="registrynumber" id="registrynumber" class="form-control"
                                aria-describedby="helpId">
                            <small id="helpId" class="text-muted">Registry number of the company (max res: 250*250)</small>
                        </div>
                        <div class="mb-3">
                            <label for="taxnumber" class="form-label">Taxnumber number</label>
                            <input type="text" name="taxnumber" id="taxnumber" class="form-control"
                                aria-describedby="helpId">
                            <small id="helpId" class="text-muted">Tax number of the company (max res: 250*250)</small>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/workplaces/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card bg-dark text-white border-secondary">
                <div class="card-body">
                    <h4 class="card-title">Create a Workplace</h4>
                    <p class="card-text text-warning">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('workplaces.update', $resource) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" name="name" id="name" class="form-control @if($errors->has('name')) border border-danger @endif"
                                placeholder="Course Name" aria-describedby="helpId" value="{{old('name', $resource->name)}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-warning">The name of the course to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="location" class="form-label">Location</label>
                            <input type="text" name="location" id="location" class="form-control"
                                placeholder="Address of your company" aria-describedby="helpId" maxlength="255" value="{{old('location', $resource->location)}}">
                            <small id="helpId" class="text-warning">Short address of the location (255 chars)</small>
                        </div>
                        <div class="mb-3">
                            <label for="registrynumber" class="form-label">Registry number</label>
                            <input type="text" name="registrynumber" id="registrynumber" class="form-control"
                                aria-describedby="helpId" value="{{old('registrynumber', $resource->registrynumber)}}">
                            <small id="helpId" class="text-warning">Registry number of the company (max res: 250*250)</small>
                        </div>
                        <div class="mb-3">
                            <label for="taxnumber" class="form-label">Taxnumber number</label>
                            <input type="text" name="taxnumber" id="taxnumber" class="form-control"
                                aria-describedby="helpId" value="{{old('taxnumber', $resource->taxnumber)}}">
                            <small id="helpId" class="text-warning">Tax number of the company (max res: 250*250)</small>
                        </div>
                        <button type="submit" class="btn form-button">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/workplaces/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            @if (Session::has('success'))
                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                    <strong>Holy guacamole!</strong>
                    <p>{{ Session::get('success') }}</p>
                </div>
            @endif
            {{-- Táblázat eleje --}}
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Address</th>
                            <th scope="col">Registry Number</th>
                            <th scope="col">Tax Number</th>
                            <th colspan="3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($resources as $item)
                            <tr class="">
                                <td scope="row">{{ $item->name }}</td>
                                <td>{{ $item->location }}</td>
                                <td>{{ $item->registrynumber }}</td>
                                <td>{{ $item->taxnumber }}</td>
                                <td>
                                    <form action="{{ route('workplaces.show', $item) }}" method="get">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('workplaces.edit', $item) }}" method="get">
                                        @csrf
                                        <button type="submit" class="btn btn-danger">Edit</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('workplaces.destroy', $item) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-warning">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            {{-- Táblázat vége --}}
        </div>
        <div class="col-2"></div>
    </div>
@endsection

resources/views/workplaces/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card bg-dark text-white border-secondary">
            <div class="card-body">
                <h4 class="card-title">{{$workplace->name}}</h4>
                <p>A munkahely neve: {{$workplace->name}}</p>
                <p>A munkahely címe: {{$workplace->location}}</p>
                <p>A munkahely cégjegyzékszáma: {{$workplace->registrynumber}}</p>
                <p>A munkahely adószáma: {{$workplace->taxnumber}}</p>
                
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

@endsection

resources/views/workplaces/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1>Deleted courses</h1>
            <div class="table-responsive-xl">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Workplace name</th>
                            <th scope="col">Workplace Location</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($workplaces as $item)
                            <tr class="">
                                <td scope="row">{{$item->name}}</td>
                                <td>{{$item->location}}</td>
                                <td>
                                    <form action="{{ route('workplaces.restore', ['workplace' => $item]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info">Restore</button>
                                    </form>                                    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
@endsection