routes/web.php
<?php

use App\Http\Controllers\EmailController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\TeacherController;
use App\Http\Middleware\Authenticate;
use App\Http\Middleware\VerifyUserRole;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/*
|--------------------------------------------------------------------------
| Landing route and landing page
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return view('landing');
})->name('landing');

/*
|--------------------------------------------------------------------------
| Authentication routes and landing page
|--------------------------------------------------------------------------
*/

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(Authenticate::class)->group(function () {
    /*
    |--------------------------------------------------------------------------
    | Courses routes
    |--------------------------------------------------------------------------
    */

    Route::resource('/courses', App\Http\Controllers\CourseController::class);
    Route::get('/course/show_deleted', [App\Http\Controllers\CourseController::class, 'show_deleted'])->name('courses.show_deleted');
    Route::put('/courses/restore/{course}', [App\Http\Controllers\CourseController::class, 'restore'])->name('courses.restore')->withTrashed();

    /*
    |--------------------------------------------------------------------------
    | Workplace routes
    |--------------------------------------------------------------------------
    */

    Route::get('/workplaces/show_deleted', [App\Http\Controllers\WorkplaceController::class, 'show_deleted'])->name('workplaces.show_deleted');
    Route::put('/workplaces/restore/{workplace}', [App\Http\Controllers\WorkplaceController::class, 'restore'])->name('workplaces.restore')->withTrashed();
    Route::resource('/workplaces', App\Http\Controllers\WorkplaceController::class);

    /*
    |--------------------------------------------------------------------------
    | Lessons routes
    |--------------------------------------------------------------------------
    */
    Route::get('/lessons/show_deleted', [App\Http\Controllers\LessonController::class, 'show_deleted'])->name('lessons.show_deleted')->middleware(VerifyUserRole::class);
    Route::get('/lessons/{course}/show_lessons', [App\Http\Controllers\LessonController::class, 'show_lessons'])->name('lessons.show_lessons');
    Route::resource('/lessons', App\Http\Controllers\LessonController::class);


    /*
    |--------------------------------------------------------------------------
    | Authenticated User Routes
    |--------------------------------------------------------------------------
    */

    Route::get('user/{user}/updateprofile', [App\Http\Controllers\UserController::class, 'edit'])->name('user.edit');
    Route::put('user/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('user.update');

    /*
    |--------------------------------------------------------------------------
    | Course Review Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('/review', ReviewController::class);

});





/*
|--------------------------------------------------------------------------
| Info User Routes
|--------------------------------------------------------------------------
*/

Route::resource('/infos', InfoController::class);

//Training facility rental, Internship, Serious games, Web and Software development - aloldalt, controller nélkül
// Cím, egy képnek hely, leírás

//Custom 404 és 403 ->error oldal az oldal stílusában (Ha a workplacesnél a felhasználó role_id != 3 akkor dobjon ide)

// Kapcsolatok aloldal, üzenetküldésre, szerkesztőfelülettel (Cím, 
//alatta bal oldalt szöveg (lionsdale címe, telefon, email elérhetőség, adószám, név, ügyvezető, 
//JOBB oldalt egy kép, 
//ALATTA szövegszerkesztő (ennekcsak egy sort csináljatok és írjátok bele h szövegszerkesztő)))


/*
|--------------------------------------------------------------------------
| Teacher Routes
|--------------------------------------------------------------------------
*/

Route::resource('/teachers', TeacherController::class);

/*
|--------------------------------------------------------------------------
| Email Routes
|--------------------------------------------------------------------------
*/

Route::get('/sendConfirmation', [EmailController::class, 'sendWelcomeEmail']);

app/Models/teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Teacher extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'subjects',
        'picture',
        'email',
        'degree'
    ];
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Models\Teacher;
use App\Http\Requests\StoreteacherRequest;
use App\Http\Requests\UpdateteacherRequest;
use Intervention\Image\Facades\Image as ResizeImage;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $teachers = Teacher::all();
        return view('teachers.index', ["teachers" => $teachers]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('teachers.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreteacherRequest $request)
    {
        $teacher = new Teacher($request->all());
        $teacher->save();

        return redirect('teachers')->with('success', $teacher->name. ' added successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Teacher $teacher)
    {
        return view('teachers.show', ['teacher' => $teacher]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Teacher $teacher)
    {
        return view('teachers.edit', ['teacher' => $teacher]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateteacherRequest $request, Teacher $teacher)
    {

         /* Resize image mentés */
        /* composer require intervention/image */
        /* use Intervention\Image\Facades\Image as ResizeImage; */
    
        if ($request->picture != null) {
            $filename = 'PI_Teacher_' . $teacher->id . '.' . $request->picture->extension();

            $img = ResizeImage::make($request->picture)
                ->resize(500, 500)->save('storage/ProfileImages/' . $filename);

            $teacher->picture = $filename;
        }
     


        $teacher->name = $request->name;
        $teacher->email = $request->email;
        $teacher->degree = $request->degree;
        $teacher->subjects = $request->subjects;
        $teacher->update();
        
        return redirect('teachers')->with('success', $teacher->name. '\'s data was successfully updated.');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Teacher $teacher)
    {
        $teacher->delete();
        return redirect('teachers')->with('success', $teacher->name. ' was successfully deleted.');

    }
}

resources/views/teachers/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card bg-dark text-white border-dark">
                <div class="card-body">
                    <h4 class="card-title">Add a Teacher</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('teachers.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" name="name" id="name" class="form-control @if($errors->has('name')) border border-danger @endif"
                                placeholder="Teacher Name" aria-describedby="helpId" value="{{old('name')}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-muted">The name of the teacher to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">E-mail</label>
                            <input type="text" name="email" id="email" class="form-control"
                                placeholder="f.e. example@test.hu" aria-describedby="helpId" maxlength="255">
                            <small id="helpId" class="text-muted">The email the teacher has expertise in.</small>
                        </div>
                        <div class="mb-3">
                            <label for="degree" class="form-label">Degree</label>
                            <input type="text" name="degree" id="degree" class="form-control"
                                placeholder="f.e. example@test.hu" aria-describedby="helpId" maxlength="255">
                            <small id="helpId" class="text-muted">The degree the teacher has expertise in.</small>
                        </div>
                        <div class="mb-3">
                            <label for="subjects" class="form-label">Subjects</label>
                            <input type="text" name="subjects" id="subjects" class="form-control"
                                placeholder="f.e. Web development" aria-describedby="helpId" maxlength="255">
                            <small id="helpId" class="text-muted">The subjects the teacher has expertise in.</small>
                        </div>
                        <div class="mb-3">
                            <label for="picture" class="form-label">Profil image</label>
                            <input type="file" name="picture" id="picture" class="form-control"
                                aria-describedby="helpId">
                            <small id="helpId" class="text-muted">Portrait image of the teacher</small>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-warning">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/teachers/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card bg-dark text-white border-dark">
                <div class="card-body">
                    <h4 class="card-title">Add a Teacher</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('teachers.update', $teacher) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" name="name" id="name" class="form-control @if($errors->has('name')) border border-danger @endif"
                                placeholder="Teacher Name" aria-describedby="helpId" value="{{old('name', $teacher->name)}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-muted">The name of the teacher to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">E-mail</label>
                            <input type="text" name="email" id="email" class="form-control"
                                placeholder="f.e. example@test.hu" aria-describedby="helpId" maxlength="255" value="{{old('email', $teacher->email)}}"> 
                            <small id="helpId" class="text-muted">The email the teacher has expertise in.</small>
                        </div>
                        <div class="mb-3">
                            <label for="degree" class="form-label">Degree</label>
                            <input type="text" name="degree" id="degree" class="form-control"
                                placeholder="f.e. example@test.hu" aria-describedby="helpId" maxlength="255" value="{{old('degree', $teacher->degree)}}">
                            <small id="helpId" class="text-muted">The degree the teacher has expertise in.</small>
                        </div>
                        <div class="mb-3">
                            <label for="subjects" class="form-label">Subjects</label>
                            <input type="text" name="subjects" id="subjects" class="form-control"
                                placeholder="f.e. Web development" aria-describedby="helpId" maxlength="255" value="{{old('subjects', $teacher->subjects)}}">
                            <small id="helpId" class="text-muted">The subjects the teacher has expertise in.</small>
                        </div>
                        <div class="mb-3">
                            <label for="picture" class="form-label">Profil image</label>
                            <input type="file" name="picture" id="picture" class="form-control"
                                aria-describedby="helpId">
                            <small id="helpId" class="text-muted">Portrait image of the teacher</small>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-warning">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/teachers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                    <strong>Holy guacamole!</strong>
                    <p>{{ Session::get('success') }}</p>
                </div>
            @endif
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Teacher name</th>
                            <th scope="col">Teacher subjects</th>
                            <th scope="col" colspan="3">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($teachers as $item)
                            <tr class="">
                                <td scope="row">{{ $item->name }}</td>
                                <td>{{ $item->subjects }}</td>
                                <td>
                                    <form action="{{ route('teachers.edit', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('teachers.destroy', $item) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                                <td>

                                    <form action="{{ route('teachers.show', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show data</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        
        </div>
        <div class="col-2"></div>
    </div>
@endsection

resources/views/teachers/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card bg-dark text-white border-dark">
            <div class="card-body text-center">
                <h4 class="card-title">{{$teacher->name}}</h4>

                <img class="img-fluid mb-3" src="{{asset('storage/ProfileImages/'.$teacher->picture)}}" alt="Teacher Profile Image">
                <p>Teacher name: {{$teacher->name}}</p>
                <p>Teacher degree: {{$teacher->degree}}</p>
                <p>Teacher email: {{$teacher->email}}</p>
                <p>Teacher subjects: {{$teacher->subjects}}</p>
                
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

@endsection

resources/views/teachers/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    
@endsection