routes/web.php
<?php

use App\Http\Controllers\EmailController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\TeacherController;
use App\Http\Middleware\Authenticate;
use App\Http\Middleware\VerifyUserRole;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/*
|--------------------------------------------------------------------------
| Landing route and landing page
|--------------------------------------------------------------------------
*/

Route::get('/', function () {
    return view('landing');
})->name('landing');

/*
|--------------------------------------------------------------------------
| Authentication routes and landing page
|--------------------------------------------------------------------------
*/

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(Authenticate::class)->group(function () {
    /*
    |--------------------------------------------------------------------------
    | Courses routes
    |--------------------------------------------------------------------------
    */

    Route::resource('/courses', App\Http\Controllers\CourseController::class);
    Route::get('/course/show_deleted', [App\Http\Controllers\CourseController::class, 'show_deleted'])->name('courses.show_deleted');
    Route::put('/courses/restore/{course}', [App\Http\Controllers\CourseController::class, 'restore'])->name('courses.restore')->withTrashed();

    /*
    |--------------------------------------------------------------------------
    | Workplace routes
    |--------------------------------------------------------------------------
    */

    Route::get('/workplaces/show_deleted', [App\Http\Controllers\WorkplaceController::class, 'show_deleted'])->name('workplaces.show_deleted');
    Route::put('/workplaces/restore/{workplace}', [App\Http\Controllers\WorkplaceController::class, 'restore'])->name('workplaces.restore')->withTrashed();
    Route::resource('/workplaces', App\Http\Controllers\WorkplaceController::class);

    /*
    |--------------------------------------------------------------------------
    | Lessons routes
    |--------------------------------------------------------------------------
    */
    Route::get('/lessons/show_deleted', [App\Http\Controllers\LessonController::class, 'show_deleted'])->name('lessons.show_deleted')->middleware(VerifyUserRole::class);
    Route::get('/lessons/{course}/show_lessons', [App\Http\Controllers\LessonController::class, 'show_lessons'])->name('lessons.show_lessons');
    Route::resource('/lessons', App\Http\Controllers\LessonController::class);


    /*
    |--------------------------------------------------------------------------
    | Authenticated User Routes
    |--------------------------------------------------------------------------
    */

    Route::get('user/{user}/updateprofile', [App\Http\Controllers\UserController::class, 'edit'])->name('user.edit');
    Route::put('user/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('user.update');

    /*
    |--------------------------------------------------------------------------
    | Course Review Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('/review', ReviewController::class);

});





/*
|--------------------------------------------------------------------------
| Info User Routes
|--------------------------------------------------------------------------
*/

Route::resource('/infos', InfoController::class);

//Training facility rental, Internship, Serious games, Web and Software development - aloldalt, controller nélkül
// Cím, egy képnek hely, leírás

//Custom 404 és 403 ->error oldal az oldal stílusában (Ha a workplacesnél a felhasználó role_id != 3 akkor dobjon ide)

// Kapcsolatok aloldal, üzenetküldésre, szerkesztőfelülettel (Cím, 
//alatta bal oldalt szöveg (lionsdale címe, telefon, email elérhetőség, adószám, név, ügyvezető, 
//JOBB oldalt egy kép, 
//ALATTA szövegszerkesztő (ennekcsak egy sort csináljatok és írjátok bele h szövegszerkesztő)))


/*
|--------------------------------------------------------------------------
| Teacher Routes
|--------------------------------------------------------------------------
*/

Route::resource('/teachers', TeacherController::class);

/*
|--------------------------------------------------------------------------
| Email Routes
|--------------------------------------------------------------------------
*/

Route::get('/sendConfirmation', [EmailController::class, 'sendWelcomeEmail']);

resources/views/courses/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card border-secondary">
                <div class="card-body">
                    <h4 class="card-title">Create a Course</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('courses.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" name="name" id="name" class="form-control @if($errors->has('name')) border border-danger @endif"
                                placeholder="Course Name" aria-describedby="helpId" value="{{old('name')}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-muted">The name of the course to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <input type="text" name="description" id="description" class="form-control"
                                placeholder="f.e. PHP beginner tutorial" aria-describedby="helpId" maxlength="255">
                            <small id="helpId" class="text-muted">Short summary of the course (255 chars)</small>
                        </div>
                        <div class="mb-3">
                            <label for="thumbnail" class="form-label">Thumbnail image</label>
                            <input type="file" name="thumbnail" id="thumbnail" class="form-control"
                                aria-describedby="helpId">
                            <small id="helpId" class="text-muted">Image of the course (max res: 250*250)</small>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/courses/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card border-secondary">
                <div class="card-body">
                    <h4 class="card-title">Edit a Course named: {{$course->name}}</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('courses.update', $course) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="name" class="form-label">Name</label>
                            <input type="text" name="name" id="name" class="form-control @if($errors->has('name')) border border-danger @endif"
                                placeholder="Course Name" aria-describedby="helpId" value="{{old('name', $course->name)}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-muted">The name of the course to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <input type="text" name="description" id="description" class="form-control"
                                placeholder="f.e. PHP beginner tutorial" aria-describedby="helpId" maxlength="255" value="{{old('description', $course->description)}}">
                            <small id="helpId" class="text-muted">Short summary of the course (255 chars)</small>
                        </div>
                        <div class="mb-3">
                            <label for="thumbnail" class="form-label">Thumbnail image</label>
                            <input type="file" name="thumbnail" id="thumbnail" class="form-control"
                                aria-describedby="helpId">
                            <small id="helpId" class="text-muted">Image of the course (max res: 250*250)</small>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/courses/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-5">
        <div class="col-2"></div>
        <div class="col-8">
            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                    <strong>Holy guacamole!</strong>
                    <p>{{ Session::get('success') }}</p>
                </div>
            @endif
            <div class="table-responsive-xl">
                <table class="table table-dark" id="courseTable">
                    <thead>
                        <tr>
                            <th scope="col">Course name</th>
                            <th scope="col">Course Description</th>
                            <th scope="col">Actions</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($courses as $item)
                            <tr class="">
                                <td scope="row">{{ $item->name }}</td>
                                <td>{{ $item->description }}</td>
                                <td>
                                    <form action="{{ route('courses.edit', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('courses.destroy', $item) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                                <td>

                                    <form action="{{ route('courses.show', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show data</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>

{{--     <div class="row mt-5">
        <div class="col-2"></div>
        <div class="col-8">
            <div id="calendar" style="background-color: #212521"></div>
        </div>
        <div class="col-2"></div>
    </div> --}}

{{--     <script>
        $(document).ready(function() {
            $('#courseTable').DataTable({
                "language": {
                    "search": "Keresés: ",
                    "lengthMenu": "_MENU_ sor mutatása",
                    "zeroRecords": "Nothing found - sorry",
                    "info": "Showing page _PAGE_ of _PAGES_",
                    "infoEmpty": "No records available",
                    "infoFiltered": "(filtered from _MAX_ total records)"
                },
                ordering: false,
            });
        });

        /*         let table = new DataTable('#courseTable');
         */
    </script>
    {{-- 
    <script>
        let courseData = <?php echo json_encode($courses); ?>;
        console.log(courseData);

        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                /* Tulajdonságok eleje */
                themeSystem: 'bootstrap5',

                initialView: 'dayGridMonth',
                selectable: true,
                editable: true,
                dayMaxEvents: true,
                events: [
                    <?php
                    for ($i = 0; $i < count($courses); $i++) {
                        echo "{title: '" . $courses[$i]->name . "', start: '2024-01-2" . $i . "',end: '2018-01-24',allDay: false},";
                    } ?>
                ],
                dateClick: function(info) {
                    alert('Date: ' + info.dateStr);
                    alert('Resource ID: ' + info.resource.id);
                },
                eventClick: function(info) {
                    alert('Event is clicked');
                }

                /* Tulajdonságok vége */
            });
            calendar.render();
        });
    </script> --}}

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                timeZone: 'UTC',
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },
                editable: true,
                dayMaxEvents: true, // when too many events in a day, show the popover
                events: [{ // this object will be "parsed" into an Event Object
                    title: 'The Title', // a property!
                    start: '2024-01-01', // a property!
                    end: '2024-01-02T23:59:59' // a property! ** see important note below about 'end' **
                }]
            });

            calendar.render();
        });
    </script> --}}
@endsection

resources/views/courses/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card border-secondary">
            <div class="card-body">
                <h4 class="card-title">{{$course->name}}</h4>

                <img src="{{$course->thumbnail}}" alt="kurzuskepe">
                <p>A kurzus neve: {{$course->name}}</p>
                <p>A kurzus leírása: {{$course->description}}</p>
                
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

@endsection

resources/views/courses/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1>Deleted courses</h1>
            <div class="table-responsive-xl">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Course name</th>
                            <th scope="col">Course Description</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($courses as $item)
                            <tr class="">
                                <td scope="row">{{$item->name}}</td>
                                <td>{{$item->description}}</td>
                                <td>
                                    <form action="{{ route('courses.restore', ['course' => $item]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info">Restore</button>
                                    </form>                                    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
@endsection